// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxpeumpvwqgmsajilrzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14cGV1bXB2d3FnbXNhamlscnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDg5MjAsImV4cCI6MjA2NTY4NDkyMH0.ZRuqnZmG4vMykpmVZQBhMpqZyiB3vtCPHtfKHKGamIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);